# Generated by Django 2.2.6 on 2019-11-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191112_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='product_id',
            new_name='post_id',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
    ]
