# Generated by Django 2.2.6 on 2019-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='thumbnail',
        ),
    ]
